trigger: none
pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfsec
    displayName: tfsec
    jobs: 
      - job: tfsec
        displayName: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
  - stage: terraforminitplan
    displayName: terraform initplan
    jobs: 
      - job: terraforminitplan
        displayName: terraform initplan
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Terraform-AzureConnection'
            backendAzureRmResourceGroupName: 'ajrg1'
            backendAzureRmStorageAccountName: 'ajstg'
            backendAzureRmContainerName: 'ajcontainer'
            backendAzureRmKey: 'terraform.tfstate'

